nginx:
    build: nginx
    restart: always
    volumes:
        - ./var/www:/usr/share/nginx/html
    ports:
        - 8010:80
    links:
        - php

php:
    build: php-fpm
    restart: always
    volumes:
        - ./var/www:/var/www
    ports:
        - 9000:9000
