nginx:
    build: nginx
    restart: always
    volumes:
        - ./var/www:/usr/share/nginx/html
    ports:
        - 8010:80
    links:
        - php

php:
    build: php-fpm
    restart: always
    volumes:
        - ./var/www:/var/www
    ports:
        - 9000:9000
    links:
        - db

db:
    image: mariadb
    ports:
        - 3305:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: root
        MYSQL_PASSWORD: root


